# Generated by Django 5.2.2 on 2025-06-06 18:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Booking'},
        ),
        migrations.AddField(
            model_name='booking',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 6, 18, 49, 22, 997245, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=datetime.datetime(2025, 6, 6, 18, 49, 49, 357160, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='bookins', to='app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=435, on_delete=django.db.models.deletion.CASCADE, related_name='bookins', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
